/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_place_placeviewer_systems_region_jni_NativeRegion */

#ifndef _Included_dev_place_placeviewer_systems_region_jni_NativeRegion
#define _Included_dev_place_placeviewer_systems_region_jni_NativeRegion
#ifdef __cplusplus
extern "C" {
#endif
  /*
   * Class:     dev_place_placeviewer_systems_region_jni_NativeRegion
   * Method:    initialize
   * Signature: (Ljava/lang/String;)V
   */
  JNIEXPORT void JNICALL Java_dev_place_placeviewer_systems_region_jni_NativeRegion_initialize
    (JNIEnv *, jclass, jstring);

  /*
   * Class:     dev_place_placeviewer_systems_region_jni_NativeRegion
   * Method:    newRegionFromDisk
   * Signature: (Ljava/lang/String;III)J
   */
  JNIEXPORT jlong JNICALL Java_dev_place_placeviewer_systems_region_jni_NativeRegion_newRegionFromDisk
    (JNIEnv *, jclass, jstring, jint, jint, jint);

  /*
   * Class:     dev_place_placeviewer_systems_region_jni_NativeRegion
   * Method:    freeRegion
   * Signature: (J)V
   */
  JNIEXPORT void JNICALL Java_dev_place_placeviewer_systems_region_jni_NativeRegion_freeRegion
    (JNIEnv *, jclass, jlong);

  /*
   * Class:     dev_place_placeviewer_systems_region_jni_NativeRegion
   * Method:    createChunkDataPacket
   * Signature: (JIIIJ)[B
   */
  JNIEXPORT jbyteArray JNICALL Java_dev_place_placeviewer_systems_region_jni_NativeRegion_createChunkDataPacket
    (JNIEnv *, jclass, jlong, jint, jint, jint, jlong);

  /*
   * Class:     dev_place_placeviewer_systems_region_jni_NativeRegion
   * Method:    createEmptyChunkData
   * Signature: (I)[B
   */
  JNIEXPORT jbyteArray JNICALL Java_dev_place_placeviewer_systems_region_jni_NativeRegion_createEmptyChunkData
    (JNIEnv *, jclass, jint);

  /*
   * Class:     dev_place_placeviewer_systems_region_jni_NativeRegion
   * Method:    indexRegionEpochs
   * Signature: (J)[J
   */
  JNIEXPORT jlongArray JNICALL Java_dev_place_placeviewer_systems_region_jni_NativeRegion_indexRegionEpochs
    (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
